export const SET_LOADING = "SET_LOADING";
export const AXIOS_SUCCESS = "AXIOS_SUCCESS";
export const AXIOS_ERROR = "AXIOS_ERROR";

export const ADD_ESTADOS = "ADD_ESTADOS";
export const ADD_ESTADOSCIVILES = "ADD_ESTADOSCIVILES";
export const ADD_PAISES = "ADD_PAISES";
export const ADD_ESTUDIOS = "ADD_ESTUDIOS";
export const ADD_TIPOSDOCUMENTO = "ADD_TIPOSDOCUMENTO";
export const ADD_CARGOS = "ADD_CARGOS";
export const ADD_TAREASDESEMPEÑADAS = "ADD_TAREASDESEMPEÑADAS";
export const ADD_PARENTESCOS = "ADD_PARENTESCOS";
export const ADD_FORMASPAGO = "ADD_FORMASPAGO";
export const ADD_MODOSCONTRATACION = "ADD_MODOSCONTRATACION";
export const ADD_MODOSLIQUIDACION = "ADD_MODOSLIQUIDACION";
export const ADD_EMPLEADORES = "ADD_EMPLEADORES";

export const ADD_DOMICLIOS = "ADD_DOMICLIOS";
export const DELETE_DOMICILIO = "DELETE_DOMICILIO"

export const SAVE_TOKEN = "SAVE_TOKEN"

export const ADD_CALLES = "ADD_CALLES";
export const ADD_DEPARTAMENTOS = "ADD_DEPARTAMENTOS";
export const ADD_LOCALIDADES = "ADD_LOCALIDADES";
export const ADD_PROVINCIAS = "ADD_PROVINCIAS";
export const ADD_BARRIOS = "ADD_BARRIOS";

export const ADD_FAMILIARES = "ADD_FAMILIARES";
export const ADD_NEW_FAMILIAR = "ADD_NEW_FAMILIAR";
export const DELETE_ONE_FAMILIAR = "DELETE_ONE_FAMILIAR";


export const ADD_CONVENIOS = "ADD_CONVENIOS";
export const ADD_CATEGORIAS = "ADD_CATEGORIAS";
export const ADD_AGRUPAMIENTOS = "ADD_AGRUPAMIENTOS";
export const ADD_CENTRO_COSTO = "ADD_CENTRO_COSTO";
export const ADD_SECTOR_DEPTO = "ADD_SECTOR_DEPTO";
export const ADD_OBRAS_SOCIALES = "ADD_OBRAS_SOCIALES";
export const ADD_LUGARES_DE_PAGO = "ADD_LUGARES_DE_PAGO";
export const ADD_BANCOS = "ADD_BANCOS";
export const ADD_DIRECCIONES = "ADD_DIRECCIONES";
export const ADD_SINDICATOS = "ADD_SINDICATOS";
export const ADD_ESQUEMAS = "ADD_ESQUEMAS";
export const ADD_NUMERADORES = "ADD_NUMERADORES";


// ESTOS SON PARA POSTEAR EN LA API
export const ADD_NEW_ESCI = "ADD_NEW_ESCI";
export const ADD_NEW_ESTUDIO = "ADD_NEW_ESTUDIO";
export const ADD_NEW_TIPODOC = "ADD_NEW_TIPODOC"
export const ADD_NEW_PARENTESCO = "ADD_NEW_PARENTESCO"
export const ADD_NEW_ESTADO = "ADD_NEW_ESTADO"
export const ADD_NEW_FORMAPAGO = "ADD_NEW_FORMAPAGO"
export const ADD_NEW_CARGO = "ADD_NEW_CARGO"
export const ADD_NEW_TAREA = "ADD_NEW_TAREA"

export const ACTUALIZA_DELETE_ESTADOS_CIVILES = "ACTUALIZA_DELETE_ESTADOS_CIVILES"
// DELETE TYPES
// estados civiles
export const GET_ID_ESCI = "GET_ID_ESCI"
export const DELETE_ESCI = "DELETE_ESCI"

// estudios
export const GET_ID_ESTUDIO = "GET_ID_ESTUDIO"
export const DELETE_ESTUDIO = "DELETE_ESTUDIO"

export const GET_ID_TIPODOC = "GET_ID_TIPODOC"
export const DELETE_TIPODOC = "DELETE_TIPODOC"

// parentescos 
export const GET_ID_PARENTESCO = "GET_ID_PARENTESCO"
export const DELETE_PARENTESCO = "DELETE_PARENTESCO"

// estados para los empleados
export const GET_ID_ESTADO = "GET_ID_ESTADO"
export const DELETE_ESTADO = "DELETE_ESTADO"

// formas de pago
export const GET_ID_FORMAPAGO = "GET_ID_FORMAPAGO"
export const DELETE_FORMAPAGO = "DELETE_FORMAPAGO"
export const ADD_ADIC_LIQUIDACION = "ADD_ADIC_LIQUIDACION"

// cargos
export const GET_ID_CARGO = "GET_ID_CARGO"
export const DELETE_CARGO = "DELETE_CARGO"

// tareas desempeñadas

export const GET_ID_TAREA = "GET_ID_TAREA"
export const DELETE_TAREA = "DELETE_TAREA"

// PUT TYPES

export const PUT_ESCI = "PUT_ESCI"
export const PUT_ESTUDIO = "PUT_ESTUDIO"
export const PUT_TIPODOC = "PUT_TIPODOC"
export const PUT_PARENTESCO = "PUT_PARENTESCO"
export const PUT_ESTADO = "PUT_ESTADO"
export const PUT_FORMAPAGO = "PUT_FORMAPAGO"
export const PUT_CARGO = "PUT_CARGO"
export const PUT_TAREA = "PUT_TAREA"


export const ADD_CONCEPTOS = "ADD_CONCEPTOS";

export const ADD_DOCU_EMPL = "ADD_DOCU_EMPL";

export const DISABLED_INPUTS = "DISABLED_INPUTS";

export const ADD_DATOS_EXTRAS = "ADD_DATOS_EXTRAS";
export const ADD_INSTRUM_LEGALES = "ADD_INSTRUM_LEGALES";


export const ADD_LICENCIAS_EMPLEADOS = "ADD_LICENCIAS_EMPLEADOS"
export const ADD_NEW_LICENCIA = "ADD_NEW_LICENCIA";
export const UPDATE_LICENCIA = "UPDATE_LICENCIA"
export const DELETE_LICENCIA = "DELETE_LICENCIA"

export const ADD_NEW_DOC = "ADD_NEW_DOC";
export const DELETE_DOC = "DELETE_DOC";

export const ADD_ONE_DE = "ADD_ONE_DE"

export const SAVE_ERROR = "SAVE_ERROR"
export const SAVE_STATUS_CODE = "SAVE_STATUS_CODE"
export const SAVE_DATOS_EXTRAS_EMPLEADOS  ="SAVE_DATOS_EXTRAS_EMPLEADOS"
export const DELETE_DATO_EXTRA_EMP = "DELETE_DATO_EXTRA_EMP"

//Estados Civiles
export const ACTUALIZA_DELETE = "ACTUALIZA_DELETE";

export const ACTUALIZA_CREATE_EC = "ACTUALIZA_CREATE_EC"

export const ACTUALIZA_UPDATE_EC = "ACTUALIZA_UPDATE_EC"

//Estudios
export const ACTUALIZA_DELETE_ESTUDIOS = "ACTUALIZA_DELETE_ESTUDIOS";

export const ACTUALIZA_CREATE_ESTUDIOS = "ACTUALIZA_CREATE_ESTUDIOS"

export const ACTUALIZA_UPDATE_ESTUDIOS = "ACTUALIZA_UPDATE_ESTUDIOS"

//TiposDocumentos
export const ACTUALIZA_DELETE_TIPOSD = "ACTUALIZA_DELETE_TIPOSD";

export const ACTUALIZA_CREATE_TIPOSD= "ACTUALIZA_CREATE_TIPOSD"

export const ACTUALIZA_UPDATE_TIPOSD = "ACTUALIZA_UPDATE_TIPOSD"

//Estados
export const ACTUALIZA_DELETE_ESTADOS = "ACTUALIZA_DELETE_ESTADOS";

export const ACTUALIZA_CREATE_ESTADOS= "ACTUALIZA_CREATE_ESTADOS"

export const ACTUALIZA_UPDATE_ESTADOS = "ACTUALIZA_UPDATE_ESTADOS"

//Formas de Pago
export const ACTUALIZA_DELETE_FORMAS_PAGO = "ACTUALIZA_DELETE_FORMAS_PAGO"

export const ACTUALIZA_CREATE_FORMAS_PAGO = "ACTUALIZA_CREATE_FORMAS_PAGO"

export const ACTUALIZA_UPDATE_FORMAS_PAGO = "ACTUALIZA_UPDATE_FORMAS_PAGO"

export const GET_PAR_SUELDOS = "GET_PAR_SUELDOS"

//Calles
export const ACTUALIZA_DELETE_CALLES = "ACTUALIZA_DELETE_CALLES";

export const ACTUALIZA_CREATE_CALLES = "ACTUALIZA_CREATE_CALLES"

export const ACTUALIZA_UPDATE_CALLES = "ACTUALIZA_UPDATE_CALLES"

//Actualizar Cargos

export const ACTUALIZA_DELETE_CARGOS = "ACTUALIZA_DELETE_CARGOS"

export const ACTUALIZA_CREATE_CARGOS = "ACTUALIZA_CREATE_CARGOS"

export const ACTUALIZA_UPDATE_CARGOS = "ACTUALIZA_UPDATE_CARGOS"

//Actualizar Tareas Desempeñadas

export const ACTUALIZA_DELETE_TAREAS = "ACTUALIZA_DELETE_TAREAS"

export const ACTUALIZA_CREATE_TAREAS = "ACTUALIZA_CREATE_TAREAS"

export const ACTUALIZA_UPDATE_TAREAS = "ACTUALIZA_UPDATE_TAREAS"

//Actualizar Modos de Contratacion

export const ACTUALIZA_DELETE_MODCONTRATACION = "ACTUALIZA_DELETE_MODCONTRATACION"

export const ACTUALIZA_CREATE_MODCONTRATACION = "ACTUALIZA_CREATE_MODCONTRATACION"

export const ACTUALIZA_UPDATE_MODCONTRATACION = "ACTUALIZA_UPDATE_MODCONTRATACION"

//Actualizar Modos de Contratacion

export const ACTUALIZA_DELETE_MODLIQUIDACION = "ACTUALIZA_DELETE_MODCONTRATACION"

export const ACTUALIZA_CREATE_MODLIQUIDACION = "ACTUALIZA_CREATE_MODCONTRATACION"

export const ACTUALIZA_UPDATE_MODLIQUIDACION = "ACTUALIZA_UPDATE_MODCONTRATACION"

//Actualizar Parentesco

export const ACTUALIZA_DELETE_PARENTESCO = "ACTUALIZA_DELETE_PARENTESCO"

export const ACTUALIZA_CREATE_PARENTESCO = "ACTUALIZA_CREATE_PARENTESCO"

export const ACTUALIZA_UPDATE_PARENTESCO = "ACTUALIZA_UPDATE_PARENTESCO"

//Actualizar Provincias

export const ACTUALIZA_DELETE_PROVINCIAS = "ACTUALIZA_DELETE_PROVINCIAS"

export const ACTUALIZA_CREATE_PROVINCIAS = "ACTUALIZA_CREATE_PROVINCIAS"

export const ACTUALIZA_UPDATE_PROVINCIAS = "ACTUALIZA_UPDATE_PROVINCIAS"

//Actualizar Dptos

export const ACTUALIZA_DELETE_DPTOS = "ACTUALIZA_DELETE_DPTOS"

export const ACTUALIZA_CREATE_DPTOS = "ACTUALIZA_CREATE_DPTOS"

export const ACTUALIZA_UPDATE_DPTOS = "ACTUALIZA_UPDATE_DPTOS"

//Actualizar Localidades

export const ACTUALIZA_DELETE_LOCALIDADES = "ACTUALIZA_DELETE_LOCALIDADES"

export const ACTUALIZA_CREATE_LOCALIDADES = "ACTUALIZA_CREATE_LOCALIDADES"

export const ACTUALIZA_UPDATE_LOCALIDADES = "ACTUALIZA_UPDATE_LOCALIDADES"

//Actualizar Barrios

export const ACTUALIZA_DELETE_BARRIOS = "ACTUALIZA_DELETE_BARRIOS"

export const ACTUALIZA_CREATE_BARRIOS = "ACTUALIZA_CREATE_BARRIOS"

export const ACTUALIZA_UPDATE_BARRIOS = "ACTUALIZA_UPDATE_BARRIOS"

//Actualizar Paises

export const ACTUALIZA_DELETE_PAISES = "ACTUALIZA_DELETE_PAISES"

export const ACTUALIZA_CREATE_PAISES = "ACTUALIZA_CREATE_PAISES"

export const ACTUALIZA_UPDATE_PAISES = "ACTUALIZA_UPDATE_PAISES"

export const UPDATE_DOMICILIO = "UPDATE_DOMICILIO"

export const GET_ARCHIVOS_ADJUNTOS = "GET_ARCHIVOS_ADJUNTOS"
export const ARCHIVOS_DOC_EMPLEADO = "ARCHIVOS_DOC_EMPLEADO"
export const ADD_NEW_ARCHIVO = "ADD_NEW_ARCHIVO"
export const ARCHIVO_DOC_SELECTED = "ARCHIVO_DOC_SELECTED"
export const ACTUALIZA_UPDATE_ARCHIVO = "ACTUALIZA_UPDATE_ARCHIVO"
export const ACTUALIZA_DELETE_ARCHIVO = "ACTUALIZA_DELETE_ARCHIVO"
export const GET_MOTIVOS_EGRESO = "GET_MOTIVOS_EGRESO"

